### ISSUE TITLE
Problem with stats::update_progress

### ISSUE THREAD

**Issue by etnt** [CleanCut/pipeviewer#1]
Hi, I've been following your course to much enjoyment :-)
However, I ran into some troubles when trying to get the colorization of the output to work.
With crossterm "0.14.2" it works but I get a warning (I'm using rustc 1.60.0 on a Linux box):

    warning: use of deprecated associated function `std::error::Error::description`: use the Display impl or to_string()
      --> src/stats.rs:44:13
       |
    44 |       let _ = execute!(
       |  _____________^
    45 | |         stderr,
    46 | |         cursor::MoveToColumn(0),
    47 | |         Clear(ClearType::CurrentLine),
    ...  |
    50 | |         PrintStyledContent(rate)
    51 | |     );
       | |_____^
       |
       = note: `#[warn(deprecated)]` on by default
       = note: this warning originates in the macro `write_ansi_code` (in Nightly builds, run with -Z macro-backtrace for more info)
so I thought I should be clever and see if a newer version of crossterm fixes this warning, so I tried version "0.23.2" (where I had to bring in style::Stylized). This made the warning go away, but now the progress output won't go back to column 0 so it just wanders off to the right.
No biggie perhaps, but I thought I should let you know.
Cheers, Toby

**Comment by CleanCut** [comment]
Good to know!

The course is published through Packt, and they control the content now, so I'm not able to do updates to the course itself. However, we could update things here and figure out what needs to change and document it for folks. 🤔

**Comment by etnt** [comment]
That could be a good idea. Packages evolve and it would be nice if the course exercise could be run on later versions of the dependencies. I'm also a bit curious to know why the output started to wander off to the right.

**Comment by CleanCut** [comment]
I found the problem! In crossterm >= 0.23 the `MoveToColumn` command ignores input of 0. The first column is not column 0, it's column 1. So in `src/stats.rs` we need to make this change:

```diff
-        cursor::MoveToColumn(0),
+        cursor::MoveToColumn(1),
```

**Comment by CleanCut** [comment]
I just pushed up the update! I added details about all the changes to [the readme](https://github.com/CleanCut/pipeviewer#update-2022-06-17)
